config/routes.rb
Rails.application.routes.draw do
  get 'grid', to: 'game#grid'

  get 'score', to: 'game#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
require 'open-uri'
require 'json'
require 'time'


class GameController < ApplicationController
  def grid
    @start_time = Time.now
    @random_grid = 9.times.map{ ('A'..'Z').to_a.sample}.join(" ")

  end

  def score
    @end_time = Time.now
    @start_time = Time.parse(params[:start])
    @answer = params[:query].upcase
    @grid = params[:grid].gsub(/\s+/, "")

    @result = run_game
  end
private

    def grid_check(attempt, grid)
      count = 0
      new_attempt = attempt.split("")
      new_attempt.each do |x|
        if grid.include? x
          count += 1
        end
      end
      if
        count == attempt.length
        return true
      else
        return false
      end
    end

    def run_game

      if grid_check(@answer, @grid) == true
        total_time = @end_time - @start_time
        result = {time: total_time}

        url = "https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=64a07d5c-f770-4030-87d9-9158b89049d4&input=#{@answer}"
        user_serialized = open(url).read
        user = JSON.parse(user_serialized)
        result[:translation] = user["outputs"][0]["output"]
        result[:score] = (@answer.length.to_f/total_time.to_f).round(3)
        if result[:score] > 1
          result[:message] = "Good catch!"
        else
          result[:message] = "Well done!"
        end
        result

      else
        result = {message: "Try again"}
      end

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/grid.html.erb
<h1 style="text-align: center;"><%= @random_grid %></h1>
<h2 style="text-align: center;"><% @start_time%></h2>

<form action="score/" style="text-align: center; margin-top: 100px;">
  <label for="question">Enter your word</label>
  <input type="hidden" value="<%= @start_time%>"  name="start">
  <input type="hidden" value="<%= @random_grid%>" name="grid">
  <input type="text" id="question" name="query" placeholder="your word">
  <input type="submit" value="Calculate!">
</form>

app/views/game/score.html.erb
<div style="text-align: center; margin-top: 50px">

<h1> <%=@result[:translation]%></h1>
<h1> <%=@result[:score]%> </h1>
<h1> <%= @result[:message] %></h1>

<%= link_to "try again", grid_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>